"""Add credit transactions and session ratings

Revision ID: 408db7b246c7
Revises: e226e4b7fb02
Create Date: 2025-10-23 17:35:27.230216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408db7b246c7'
down_revision: Union[str, None] = 'e226e4b7fb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('rated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['rated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'rated_by')
    op.drop_column('sessions', 'feedback')
    op.drop_column('sessions', 'rating')
    # ### end Alembic commands ###
